Dev spring boot book tests
OlegTuryk/online-book-store pull request #12
Opened 2023-09-29 05:38 UTC by OlegTuryk

2023-10-04 12:51 UTC, andrii-hoienko requested changes
GJ! But still, some improvements required

2023-10-04 12:51 UTC, andrii-hoienko commented on src/test/java/com/app/onlinebookstore/controller/BookControllerTest.java
> +        CREATE_BOOK_REQUEST_DTO.setTitle("Test Title1");
Please create constants wich fields will be populated and reuse them in test methods

2023-10-04 12:51 UTC, andrii-hoienko commented on src/test/java/com/app/onlinebookstore/controller/BookControllerTest.java
> +        Assertions.assertNotNull(actual);
please use static import

2023-10-04 12:51 UTC, andrii-hoienko commented on src/test/java/com/app/onlinebookstore/controller/BookControllerTest.java
> +        assertTrue(EqualsBuilder.reflectionEquals(bookDto, actual, "id"));
What is the reason to use 'assertTrue(EqualsBuilder.reflectionEquals(...' is it possible to assertEquals?

2023-10-04 12:51 UTC, andrii-hoienko commented on src/test/java/com/app/onlinebookstore/service/BookServiceTest.java
> +        when(bookMapper.toModel(createBookRequestDto)).thenReturn(book);
To make test more readable separate with empty lines precondition, action and assertion

2023-10-04 12:51 UTC, andrii-hoienko commented on src/test/java/com/app/onlinebookstore/service/BookServiceTest.java
> +        assertThrows(EntityNotFoundException.class, () -> bookService.getById(nonExistentId));
Check error message as well

2023-10-04 12:51 UTC, andrii-hoienko commented on src/test/java/com/app/onlinebookstore/service/BookServiceTest.java
> +        verify(bookRepository, times(1)).deleteById(TEST_ID);
times(1) set by default

2023-10-04 12:51 UTC, andrii-hoienko commented on src/test/resources/database/delete/delete-book-and-category-data.sql
> +DELETE FROM categories;
empty line

2023-10-18 15:58 UTC, vovasalyha approved these changes

2023-10-20 15:58 UTC, merged