Dev spring boot readme
OlegTuryk/online-book-store pull request #13
Opened 2023-10-16 14:06 UTC by OlegTuryk

2023-10-16 15:37 UTC, vovasalyha requested changes
GJ. Where is Loom video?Also, if possible, make your readme more engaging by adding some visuals etc.

2023-10-16 15:37 UTC, vovasalyha commented on readme.md
> +- [MySQL database](https://www.mysql.com/downloads/)
not required if running with docker

2023-10-16 15:37 UTC, vovasalyha commented on readme.md
> +- [Maven](https://maven.apache.org/download.cgi)
not required if using maven wrapper

2023-10-23 11:51 UTC, andrii-hoienko approved these changes
GJ!

2023-10-23 16:29 UTC, merged