Replace BookRepository with JpaRepository add liquebase support, add …
OlegTuryk/online-book-store pull request #3
Opened 2023-09-07 12:28 UTC by OlegTuryk

…softdelete concept

2023-09-08 09:05 UTC, DmytroV95 requested changes
GJ! Interesting solution. Let's improve it!

2023-09-08 09:05 UTC, DmytroV95 commented on src/main/java/com/app/onlinebookstore/specifications/BookSpecifications.java
> +        return (root, query, cb) -> {
I think it's a more understandable name of argument.
```suggestion
        return (root, query, criteriaBuilder) -> {
```

2023-09-08 09:05 UTC, DmytroV95 commented on src/main/java/com/app/onlinebookstore/specifications/BookSpecifications.java
> +                predicates.add(cb.equal(root.get("author"), searchParameters.getAuthor()));
It's better to make "author"  and other values as constants.

2023-09-08 11:48 UTC, DmytroV95 approved these changes
GJ!

2023-09-08 15:19 UTC, vovasalyha approved these changes
GJ.

2023-09-08 15:58 UTC, merged

2023-10-30 13:19 UTC, andrii-hoienko reviewed
GJ!